### ISSUE TITLE
Offline Bot

### ISSUE THREAD

**Issue by teojmciver** [nickbetsworth/MSW-Discord-Bot#1]
I wasn’t sure where else to put this so I’m putting it here. I added the bot to my discord server and tried running the command: `!msw pacific beach` and `!msw “pacific beach”` in a few different channels the bot was in but the bot remained offline and it didn’t work.

**Comment by nickbetsworth** [comment]
Hi,

Thanks for bringing this to my attention! It looks as though the server the bot was hosted on was down and was failing to reboot.

It's back up now and the bot should appear to be online in your server.

The search syntax doesn't require quotations (`!msw pacific beach` should work fine) 

Let me know if it's fixed for you 👍
